export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';

export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT';

export const AUTH_USER_DELETE_REQUEST = 'AUTH_USER_DELETE_REQUEST';
export const AUTH_USER_DELETE_SUCCESS = 'AUTH_USER_DELETE_SUCCESS';
export const AUTH_USER_DELETE_FAILURE = 'AUTH_USER_DELETE_FAILURE';

export const AUTH_USER_LOADED = 'AUTH_USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const AUTH_FORGOT_PASSWORD_REQUEST = 'AUTH_FORGOT_PASSWORD_REQUEST';
export const AUTH_FORGOT_PASSWORD_SUCCESS = 'AUTH_FORGOT_PASSWORD_SUCCESS';
export const AUTH_FORGOT_PASSWORD_FAILURE = 'AUTH_FORGOT_PASSWORD_FAILURE';

export const AUTH_VERIFY_PASSWORD_REQUEST = 'AUTH_VERIFY_PASSWORD_REQUEST';
export const AUTH_VERIFY_PASSWORD_SUCCESS = 'AUTH_VERIFY_PASSWORD_SUCCESS';
export const AUTH_VERIFY_PASSWORD_FAILURE = 'AUTH_VERIFY_PASSWORD_FAILURE';
export const AUTH_VERIFY_PASSWORD_RESET = 'AUTH_VERIFY_PASSWORD_RESET';
// export const AUTH_UPDATE_PASSWORD_REQUEST = 'AUTH_UPDATE_PASSWORD_REQUEST';
// export const AUTH_UPDATE_PASSWORD_SUCCESS = 'AUTH_UPDATE_PASSWORD_SUCCESS';
// export const AUTH_UPDATE_PASSWORD_FAILURE = 'AUTH_UPDATE_PASSWORD_FAILURE';
// export const AUTH_UPDATE_PASSWORD_RESET = 'AUTH_UPDATE_PASSWORD_RESET';

export const AUTH_NEW_PASSWORD_REQUEST = 'AUTH_NEW_PASSWORD_REQUEST';
export const AUTH_NEW_PASSWORD_SUCCESS = 'AUTH_NEW_PASSWORD_SUCCESS';
export const AUTH_NEW_PASSWORD_FAILURE = 'AUTH_NEW_PASSWORD_FAILURE';

export const TOKEN_REQUEST = 'TOKEN_REQUEST';
export const TOKEN_RECEIVED = 'TOKEN_RECEIVED';
export const TOKEN_FAILURE = 'TOKEN_FAILURE';