export const SLIDE_LIST_REQUEST = 'SLIDE_LIST_REQUEST';
export const SLIDE_LIST_SUCCESS = 'SLIDE_LIST_SUCCESS';
export const SLIDE_LIST_FAILURE = 'SLIDE_LIST_FAILURE';

export const SLIDE_LIST_DETAILS_REQUEST = 'SLIDE_LIST_DETAILS_REQUEST';
export const SLIDE_LIST_DETAILS_SUCCESS = 'SLIDE_LIST_DETAILS_SUCCESS';
export const SLIDE_LIST_DETAILS_FAILURE = 'SLIDE_LIST_DETAILS_FAILURE';

export const SLIDE_CREATE_REQUEST = 'SLIDE_CREATE_REQUEST';
export const SLIDE_CREATE_SUCCESS = 'SLIDE_CREATE_SUCCESS';
export const SLIDE_CREATE_FAILURE = 'SLIDE_CREATE_FAILURE';
export const SLIDE_CREATE_RESET = 'SLIDE_CREATE_RESET';

export const SLIDE_UPDATE_REQUEST = 'SLIDE_UPDATE_REQUEST';
export const SLIDE_UPDATE_SUCCESS = 'SLIDE_UPDATE_SUCCESS';
export const SLIDE_UPDATE_FAILURE = 'SLIDE_UPDATE_FAILURE';
export const SLIDE_UPDATE_RESET = 'SLIDE_UPDATE_RESET';

export const SLIDE_DELETE_REQUEST = 'SLIDE_DELETE_REQUEST';
export const SLIDE_DELETE_SUCCESS = 'SLIDE_DELETE_SUCCESS';
export const SLIDE_DELETE_FAILURE = 'SLIDE_DELETE_FAILURE';